### PR TITLE
Move models and tools to packages

### PR DESCRIPTION
**Pull request by orlando**
**What:** Move models and tools to their own packages

**Why:** To be able to reuse these between the backend and other apps

**How:** Moving out models and tools from the backend/frontend apps to a top-level folder under `apps`.

### CODE REVIEW

**Comment by duranmla** [comment]
Well, this is massive, in any case as we are just moving things around it shouldn't be a problem, nevertheless, not sure if the current test approach is enough to make sure that if it is passing everything is ok.

**Comment by orlando** [comment]
We are running tests correctly (both cypress and unit tests) using the model from the **models** package in the **backend**. Tests are failing because we need to add Postgres to the CI to run migrations.

**Comment by duranmla** [comment]
Seems like way too much in a single place. Let's wrap this up and then send the updates within separated PRs

**Comment by orlando** [comment]
@duranmla This PR is ready for review, we have both the tools and models in separate packages that are going to be published to NPM. I created these tickets as follow-up

- https://github.com/debtcollective/disputes/issues/173
- https://github.com/debtcollective/disputes/issues/174
- https://github.com/debtcollective/disputes/issues/175
- https://github.com/debtcollective/disputes/issues/176

**Comment by duranmla** [comment]
What do you think about adding into the top level `README.md` a map for this along with a brief description like:

```
app/
   frontend/
   tools/
   backend/
```

This app is the one used to generate disputes. the project has been structured like so:
- Frontend: all components that are needed for the app
- Tools: schemas that define the templates in order to create a new dispute
- Backend: services needed to perform the dispute creation
- Models: Shared place to export all the validations and logic for a model within the platform.

--- 

At this point it may sound tedious and unneeded but as we are adding concepts like "Tools" it would be great to have already the base on how to document any other new concept we want to introduce. New people will be able to detect where their implementations need to live straight away and understand where to look for a base example on how to deal with some of the existing concepts.

**Comment by orlando** [comment]
@duranmla cool, I'll add that info to the README

**Pull request merged**
